<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Overview" data-toc-modified-id="Overview-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Overview</a></span></li><li><span><a href="#Import-NumPy" data-toc-modified-id="Import-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import NumPy</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Creating-a-NumPy-array:" data-toc-modified-id="Creating-a-NumPy-array:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Creating a NumPy array:</a></span><ul class="toc-item"><li><span><a href="#arange()" data-toc-modified-id="arange()-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>arange()</a></span></li><li><span><a href="#np.linspace()" data-toc-modified-id="np.linspace()-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>np.linspace()</a></span></li></ul></li><li><span><a href="#Arrays-with-Random-Numbers" data-toc-modified-id="Arrays-with-Random-Numbers-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Arrays with Random Numbers</a></span><ul class="toc-item"><li><span><a href="#Sort" data-toc-modified-id="Sort-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Sort</a></span></li><li><span><a href="#Concatenate" data-toc-modified-id="Concatenate-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Concatenate</a></span></li></ul></li><li><span><a href="#Shape-and-Reshape" data-toc-modified-id="Shape-and-Reshape-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Shape and Reshape</a></span></li><li><span><a href="#Transpose-(swap-axes)-a-matrix" data-toc-modified-id="Transpose-(swap-axes)-a-matrix-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Transpose (swap axes) a matrix</a></span></li></ul></li><li><span><a href="#Indexing,-Slicing-&amp;-Selecting" data-toc-modified-id="Indexing,-Slicing-&amp;-Selecting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Indexing, Slicing &amp; Selecting</a></span><ul class="toc-item"><li><span><a href="#Indexing-a-2d-array-(matrix)" data-toc-modified-id="Indexing-a-2d-array-(matrix)-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Indexing a 2d array (matrix)</a></span></li><li><span><a href="#Selecting-(if-time-permits)" data-toc-modified-id="Selecting-(if-time-permits)-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Selecting (if time permits)</a></span></li></ul></li><li><span><a href="#Operations" data-toc-modified-id="Operations-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Operations</a></span><ul class="toc-item"><li><span><a href="#Numpy-Array-Aggregate-Functions" data-toc-modified-id="Numpy-Array-Aggregate-Functions-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Numpy Array Aggregate Functions</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Broadcasting</a></span></li></ul></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Exercises</a></span></li></ul></div>

# Overview 

**The following information is from the NumPy documentation.**

https://numpy.org/doc/stable/user/absolute_beginners.html#

The sequence of information presented in this notebook follows the documentation sequence.

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image3_numpy.png)

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image5_array.png)

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image4_numpyarray.png)

# Import NumPy

In [59]:
import numpy as np
import pandas as pd


# Arrays

## Creating a NumPy array:

- np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [60]:
# Create an array from a list

# np.array()          #####################

nums = [2,4,5,3,9]    # Assign a list to a variable
x = np.array(nums)    # Pass the variable to the method

print(type(x))
print(np.shape(x))
print(type(nums))
print(x)

<class 'numpy.ndarray'>
(5,)
<class 'list'>
[2 4 5 3 9]


In [4]:
# Create a matrix from a list of lists

# Assign a tuple containing list to a variable
# Pass the list to the variable

nums_l = ([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54])

y =np.array(nums_l)

print(type(y))
print(np.shape(y))
print(type(nums_l))
print (y)

<class 'numpy.ndarray'>
(3, 5)
<class 'tuple'>
[[ 2  4  5  3  9]
 [ 4  7 12 34 76]
 [99 56 89 23 54]]


In [5]:
nums_l = [[2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54]]

y =np.array(nums_l)

print(type(y))
print(np.shape(y))
print(type(nums_l))

<class 'numpy.ndarray'>
(3, 5)
<class 'list'>


In [6]:
# Create an array without a variable
# Pass the lists directly to the method
# Notice the extra square brackets! A list of lists

z = np.array([[1,2,3], [3,2,1],[9,9,9]])  

print(type(z))
print(np.shape(z))

<class 'numpy.ndarray'>
(3, 3)


In [7]:
# This is an intentional failure
# Missing square brackets

z = np.array([1,2,3], [3,2,1],[9,9,9])  

print(type(z))
print(np.shape(z))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
# An array of zeros

np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# An array of ones

np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# An empty array.  Initial content is random numbers.

np.empty(2)

array([2.05833592e-312, 2.33419537e-312])

In [13]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

### arange()

In [14]:
# An array with a range of elements

y=np.arange(0,10)   # start at zero and go for 10 positions

In [15]:
type(y)


numpy.ndarray

In [16]:
np.arange(0,11,2)   # start at zero, end at eleven and increment by two

array([ 0,  2,  4,  6,  8, 10])

### np.linspace()

Return evenly spaced numbers over a specified interval.

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [20]:
np.ones(2, dtype=np.float64)

array([1., 1.])

## Arrays with Random Numbers

- np.random, np.randon.rand, np.randon.randn, np.random.randint

In [21]:
np.random                    # random is a module within numpy

<module 'numpy.random' from '/opt/anaconda3/envs/PythonIntro2024/lib/python3.12/site-packages/numpy/random/__init__.py'>

In [22]:
np.random.rand(2)            # Creates sample with a uniform distribution

array([0.83713138, 0.5512017 ])

In [23]:
np.random.seed(1234)         # Seed ensures we get the same random numbers
np.random.rand()  

0.1915194503788923

In [24]:
np.random.seed(1234)         # Seed ensures we get the same random numbers
a = np.random.randint(1,100,6)  
b = np.random.randint(1,100,6)
c = np.random.randint(1,100,6)
d = np.random.randint(1,100,6)
e = np.random.randint(1,100,6)

f = np.array([a,b,c,d,e])
f

array([[48, 84, 39, 54, 77, 25],
       [16, 50, 24, 27, 31, 44],
       [31, 27, 59, 93, 70, 81],
       [74, 48, 51, 77, 38, 35],
       [39, 68, 12,  1, 76, 81]])

In [ ]:
f[1][1]

In [ ]:
f[2:4,1:4]

In [ ]:
np.random.randn(2)           # Creates a sample using the standard normal distribution

In [ ]:
np.random.randint(1,100)     # Return random integers from low (inclusive) to high (exclusive)

In [ ]:
np.random.randint(1,100,10)

In [26]:
# You can explicity import random and then np. can be left off.

from numpy import random

In [27]:
random.seed(1234)
random.rand(2)  

array([0.19151945, 0.62210877])

### Sort

In [ ]:
my_arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(my_arr)

### Concatenate

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))
c

In [ ]:
a = np.array([[1, 2, 3, 4]])  # Notice those extra square brackets again!
b = np.array([[5, 6, 7, 8]])
d = np.concatenate((a, b))
d

In [28]:
# From the documentation

q = [[1, 2], [3, 4]]

a = np.array([[1, 2], [3, 4]])  # This is a 2x2 matrix
b = np.array([[5, 6]])          # This is a 1-d array

print(q, type(q))
print(a, type(a))
print(b, type(b))


[[1, 2], [3, 4]] <class 'list'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
[[5 6]] <class 'numpy.ndarray'>


In [29]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.concatenate((a, b), axis=None)

## Shape and Reshape

ndim, size & shape are attributes of the array (not methods).  Notice that () are not used.

In [32]:
a = np.array([[1, 2], [3, 4]])
print(a.ndim)
print(a.shape)

2
(2, 2)


In [33]:
a.size

4

In [ ]:
a.shape

In [34]:
# Reshape an array

m = np.arange(50)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
m.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
m.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

## Transpose (swap axes) a matrix

In [37]:
nums_l = ([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54])
x = np.array(nums_l)
x

array([[ 2,  4,  5,  3,  9],
       [ 4,  7, 12, 34, 76],
       [99, 56, 89, 23, 54]])

In [38]:
x.transpose()

array([[ 2,  4, 99],
       [ 4,  7, 56],
       [ 5, 12, 89],
       [ 3, 34, 23],
       [ 9, 76, 54]])

In [39]:
y = np.flip(x)
y

array([[54, 23, 89, 56, 99],
       [76, 34, 12,  7,  4],
       [ 9,  3,  5,  4,  2]])

# Indexing, Slicing & Selecting

In [40]:
m = np.arange(12)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
m[6]

6

In [42]:
m[2:5]          # Remember, 5 is not included

array([2, 3, 4])

## Indexing a 2d array (matrix)

In [43]:
m2 = np.array(([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54]))
m2

array([[ 2,  4,  5,  3,  9],
       [ 4,  7, 12, 34, 76],
       [99, 56, 89, 23, 54]])

Format is **array_name[row][col]** or **array_name[row,col]**. Comma notation is more common.

In [44]:
#Indexing row
m2[1]

array([ 4,  7, 12, 34, 76])

In [45]:
# Getting individual element value
m2[1][0]

4

In [46]:
# Getting individual element value
m2[1,0]

4

In [48]:
m2

array([[ 2,  4,  5,  3,  9],
       [ 4,  7, 12, 34, 76],
       [99, 56, 89, 23, 54]])

In [47]:
# 2D array slicing

m2[:2,1:]  # Get all values in rows 0 & 1, get all values in those rows after the first column.

array([[ 4,  5,  3,  9],
       [ 7, 12, 34, 76]])

In [50]:
m2[2,3]

23

In [ ]:
m2[2,:]

## Selecting (if time permits)

In [ ]:
m2 = np.array(([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54]))
m2

In [ ]:
m2 > 4

In [ ]:
bool_m2 = m2 > 4
bool_m2

In [ ]:
m2[bool_m2]

# Operations

In [ ]:
# Add arrays together

a = np.array([[1, 2, 3, 4]])
b = np.array([[5, 6, 7, 8]])
a+b

In [ ]:
# Perform more math on arrays
c = a*b
d = a/b
e = a-b
print(c)
print(d)
print(e)

In [ ]:
# Aggregate functions - Sum

a.sum()

In [ ]:
# Aggregate functions - min, max, mean

f = a.min()
g = a.max()
h = a.mean()
i = a.std()

print(f)
print(g)
print(h)
print(i)

## Numpy Array Aggregate Functions

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image7_aggregate.png)
https://www.pythonprogramming.in/numpy-aggregate-and-statistical-functions.html![image7_aggregate.png]

## Broadcasting

In [ ]:
a

In [ ]:
a*2

# Exercises

In [51]:
# Create an array with 20 zeros
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [53]:
# Create a 2d array with 20 zeros
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
# Create an array of 20 ones
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [55]:
# Create an array of 20 fives (requires 2 steps)
np.ones(20) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [ ]:
# Create an array with all the odd numbers between 0 and 50
np.arange(1,51,2)

In [ ]:
# Create an array with all the numbers between 15 and 50 incremented by 5



In [ ]:
# Create a 5 x 5 matrix (name it t) with numbers ranging from 5 to 25


In [ ]:
# Using indexing from t, pick out the value 22



In [ ]:
# Using t, create the following output

# array([16, 17, 18])



In [ ]:
# Using t, create the following output

# array([[15, 16, 17],
#        [20, 21, 22]])



In [ ]:
# Using t, create the following output

# array([[ 6],
#        [11],
#        [16],
#        [21]])

