<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Overview" data-toc-modified-id="Overview-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Overview</a></span></li><li><span><a href="#Import-NumPy" data-toc-modified-id="Import-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import NumPy</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Creating-a-NumPy-array:" data-toc-modified-id="Creating-a-NumPy-array:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Creating a NumPy array:</a></span><ul class="toc-item"><li><span><a href="#arange()" data-toc-modified-id="arange()-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>arange()</a></span></li><li><span><a href="#np.linspace()" data-toc-modified-id="np.linspace()-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>np.linspace()</a></span></li></ul></li><li><span><a href="#Arrays-with-Random-Numbers" data-toc-modified-id="Arrays-with-Random-Numbers-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Arrays with Random Numbers</a></span><ul class="toc-item"><li><span><a href="#Sort" data-toc-modified-id="Sort-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Sort</a></span></li><li><span><a href="#Concatenate" data-toc-modified-id="Concatenate-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Concatenate</a></span></li></ul></li><li><span><a href="#Shape-and-Reshape" data-toc-modified-id="Shape-and-Reshape-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Shape and Reshape</a></span></li><li><span><a href="#Transpose-(swap-axes)-a-matrix" data-toc-modified-id="Transpose-(swap-axes)-a-matrix-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Transpose (swap axes) a matrix</a></span></li></ul></li><li><span><a href="#Indexing,-Slicing-&amp;-Selecting" data-toc-modified-id="Indexing,-Slicing-&amp;-Selecting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Indexing, Slicing &amp; Selecting</a></span><ul class="toc-item"><li><span><a href="#Indexing-a-2d-array-(matrix)" data-toc-modified-id="Indexing-a-2d-array-(matrix)-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Indexing a 2d array (matrix)</a></span></li><li><span><a href="#Selecting-(if-time-permits)" data-toc-modified-id="Selecting-(if-time-permits)-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Selecting (if time permits)</a></span></li></ul></li><li><span><a href="#Operations" data-toc-modified-id="Operations-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Operations</a></span><ul class="toc-item"><li><span><a href="#Numpy-Array-Aggregate-Functions" data-toc-modified-id="Numpy-Array-Aggregate-Functions-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Numpy Array Aggregate Functions</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Broadcasting</a></span></li></ul></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Exercises</a></span></li></ul></div>

# Overview 

**The following information is from the NumPy documentation.**

https://numpy.org/doc/stable/user/absolute_beginners.html#

The sequence of information presented in this notebook follows the documentation sequence.

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image3_numpy.png)

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image5_array.png)

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image4_numpyarray.png)

# Import NumPy

In [ ]:
import numpy as np
import pandas as pd


# Arrays

## Creating a NumPy array:

- np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [ ]:
# Create an array from a list

# np.array()          #####################

nums = [2,4,5,3,9]    # Assign a list to a variable
x = np.array(nums)    # Pass the variable to the method

print(type(x))
print(np.shape(x))
print(type(nums))

In [ ]:
# Create a matrix from a list of lists

# Assign a list to a variable
# Pass the list to the variable

nums_l = ([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54])

y =np.array(nums_l)

print(type(y))
print(np.shape(y))
print(type(nums_l))

In [ ]:
nums_l = [[2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54]]

y =np.array(nums_l)

print(type(y))
print(np.shape(y))
print(type(nums_l))

In [ ]:
# Create an array without a variable
# Pass the lists directly to the method
# Notice the extra square brackets! A list of lists

z = np.array([[1,2,3], [3,2,1],[9,9,9]])  

print(type(z))
print(np.shape(z))

In [ ]:
# This is an intentional failure
# Missing square brackets

#z = np.array([1,2,3], [3,2,1],[9,9,9])  

#print(type(z))
#print(np.shape(z))

In [ ]:
# An array of zeros

np.zeros(3)

In [ ]:
np.zeros((5,5))

In [ ]:
# An array of ones

np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
# An empty array.  Initial content is random numbers.

np.empty(2)

In [ ]:
np.empty((2,2))

### arange()

In [ ]:
# An array with a range of elements

y=np.arange(0,10)   # start at zero and go for 10 positions

In [ ]:
type(y)


In [ ]:
np.arange(0,11,2)   # start at zero, end at eleven and increment by two

### np.linspace()

Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.linspace(0,10,50)

In [ ]:
np.ones(2, dtype=np.int64)

In [ ]:
np.ones(2, dtype=np.float64)

## Arrays with Random Numbers

- np.random, np.randon.rand, np.randon.randn, np.random.randint

In [ ]:
np.random                    # random is a module within numpy

In [ ]:
np.random.rand(2)            # Creates sample with a uniform distribution

In [ ]:
np.random.seed(1234)         # Seed ensures we get the same random numbers
np.random.rand()  

In [ ]:
np.random.seed(1234)         # Seed ensures we get the same random numbers
a = np.random.randint(1,100,6)  
b = np.random.randint(1,100,6)
c = np.random.randint(1,100,6)
d = np.random.randint(1,100,6)
e = np.random.randint(1,100,6)

f = np.array([a,b,c,d,e])
f

In [ ]:
f[1][1]

In [ ]:
f[2:4,1:4]

In [ ]:
np.random.randn(2)           # Creates a sample using the standard normal distribution

In [ ]:
np.random.randint(1,100)     # Return random integers from low (inclusive) to high (exclusive)

In [ ]:
np.random.randint(1,100,10)

In [ ]:
# You can explicity import random and then np. can be left off.

from numpy import random

In [ ]:
random.seed(1234)
random.rand(2)  

### Sort

In [ ]:
my_arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(my_arr)

### Concatenate

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))
c

In [ ]:
a = np.array([[1, 2, 3, 4]])  # Notice those extra square brackets again!
b = np.array([[5, 6, 7, 8]])
d = np.concatenate((a, b))
d

In [ ]:
# From the documentation

q = [[1, 2], [3, 4]]

a = np.array([[1, 2], [3, 4]])  # This is a 2x2 matrix
b = np.array([[5, 6]])          # This is a 1-d array

print(q, type(q))
print(a, type(a))
print(b, type(b))


In [ ]:
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b.T), axis=1)

In [ ]:
np.concatenate((a, b), axis=None)

## Shape and Reshape

ndim, size & shape are attributes of the array (not methods).  Notice that () are not used.

In [ ]:
a = np.array([[1, 2], [3, 4]])
a.ndim

In [ ]:
a.size

In [ ]:
a.shape

In [ ]:
# Reshape an array

m = np.arange(50)
m

In [ ]:
m.reshape(5,10)

In [ ]:
m.reshape(2,25)

## Transpose (swap axes) a matrix

In [ ]:
nums_l = ([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54])
x = np.array(nums_l)
x

In [ ]:
x.transpose()

In [ ]:
y = np.flip(x)
y

# Indexing, Slicing & Selecting

In [ ]:
m = np.arange(12)
m

In [ ]:
m[6]

In [ ]:
m[2:5]          # Remember, 5 is not included

## Indexing a 2d array (matrix)

In [ ]:
m2 = np.array(([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54]))
m2

Format is **array_name[row][col]** or **array_name[row,col]**. Comma notation is more common.

In [ ]:
#Indexing row
m2[1]

In [ ]:
# Getting individual element value
m2[1][0]

In [ ]:
# Getting individual element value
m2[1,0]

In [ ]:
# 2D array slicing

m2[:2,1:]  # Get all values in rows 0 & 1, get all values in those rows after the first column.

In [ ]:
m2[2]

In [ ]:
m2[2,:]

## Selecting (if time permits)

In [ ]:
m2 = np.array(([2,4,5,3,9],[4,7,12,34,76],[99,56,89,23,54]))
m2

In [ ]:
m2 > 4

In [ ]:
bool_m2 = m2 > 4
bool_m2

In [ ]:
m2[bool_m2]

# Operations

In [ ]:
# Add arrays together

a = np.array([[1, 2, 3, 4]])
b = np.array([[5, 6, 7, 8]])
a+b

In [ ]:
# Perform more math on arrays
c = a*b
d = a/b
e = a-b
print(c)
print(d)
print(e)

In [ ]:
# Aggregate functions - Sum

a.sum()

In [ ]:
# Aggregate functions - min, max, mean

f = a.min()
g = a.max()
h = a.mean()
i = a.std()

print(f)
print(g)
print(h)
print(i)

## Numpy Array Aggregate Functions

![](https://raw.githubusercontent.com/jimcody2014/python_images/main/image7_aggregate.png)
https://www.pythonprogramming.in/numpy-aggregate-and-statistical-functions.html![image7_aggregate.png]

## Broadcasting

In [ ]:
a

In [ ]:
a*2

# Exercises

In [ ]:
# Create an array with 20 zeros


In [ ]:
# Create a 2d array with 20 zeros


In [ ]:
# Create an array of 20 ones


In [ ]:
# Create an array of 20 fives (requires 2 steps)


In [ ]:
# Create an array with all the odd numbers between 0 and 50


In [ ]:
# Create an array with all the numbers between 15 and 50 incremented by 5


In [ ]:
# Create a 5 x 5 matrix (name it t) with numbers ranging from 5 to 25


In [ ]:
# Using indexing from t, pick out the value 22



In [ ]:
# Using t, create the following output

# array([16, 17, 18])



In [ ]:
# Using t, create the following output

# array([[15, 16, 17],
#        [20, 21, 22]])



In [ ]:
# Using t, create the following output

# array([[ 6],
#        [11],
#        [16],
#        [21]])

